update to wollmux-config-de-utf8-15.04.tar.gz

diff --git a/wollmux-config/scripts/make_plugins b/wollmux-config/scripts/make_plugins
--- a/wollmux-config/scripts/make_plugins
+++ b/wollmux-config/scripts/make_plugins
@@ -4,13 +4,38 @@
 scripts="${0%/*}"
 plugins="${scripts}/../plugins"
 
-OOOCLS1="/opt/openoffice.org/program/classes"
-OOOCLS2="/opt/openoffice.org/program/classes" # kann unterschiedlich sein!
-OOOJARS="$OOOCLS1/juh.jar:$OOOCLS1/jurt.jar:$OOOCLS1/ridl.jar:$OOOCLS2/unoil.jar"
+for ooo in /opt/libreoffice* /opt/openoffice*; do
+  echo "seaching for juh.jar, jurt.jar, ridl.jar and unoil.jar in $ooo"
+  juh=$(find $ooo -name "juh.jar" 2>/dev/null)
+  jurt=$(find $ooo -name "jurt.jar" 2>/dev/null)
+  ridl=$(find $ooo -name "ridl.jar" 2>/dev/null)
+  unoil=$(find $ooo -name "unoil.jar" 2>/dev/null)
+  [ "x$juh" == "x" ] || [ "x$jurt" == "x" ] || [ "x$ridl" == "x" ] || [ "x$unoil" == "x" ] || break;
+done
+
+if [ "x$juh" == "x" ] || [ "x$jurt" == "x" ] || [ "x$ridl" == "x" ] || [ "x$unoil" == "x" ]
+then
+  echo "Could not find juh.jar, jurt.jar, ridl.jar or unoil.jar on your system."
+  echo "They are all required for building some of the plugins."
+  echo "Please ensure that there is an OpenOffice/LibreOffice installation available"
+  echo "in /opt/libreoffice* or /opt/openoffice*."
+  exit 1;
+fi
+
+OOOJARS="$juh:$jurt:$ridl:$unoil"
 
 PDFBOXJARS="$plugins/commons-logging-1.1.1.jar:$plugins/pdfbox-1.5.0.jar"
 
 export CLASSPATH="$plugins:$plugins/WollMuxInterfaces.jar:$plugins/classes.jar:$PDFBOXJARS:$OOOJARS"
+
+if [ ! -x "${JAVA_HOME}/bin/javac" ]
+then
+  echo "Please set JAVA_HOME to a jdk that is able to build for target 1.6"
+  echo "This could be done e.g. like this:"
+  echo "  sudo apt-get install oracle-j2sdk1.6"
+  echo "  export JAVA_HOME=/usr/lib/jvm/j2sdk1.6-oracle"
+  exit 1;
+fi
 
 for classFile in $(find $plugins -name "*.class")
 do
@@ -23,5 +48,5 @@ do
   echo "===================================================================="
   echo "javac $javaFile"
   echo "===================================================================="
-  javac -encoding UTF-8 -target 1.5 $javaFile
+  $JAVA_HOME/bin/javac -encoding UTF-8 -target 1.6 $javaFile
 done
